name: Take Webpage Screenshot
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
    inputs:
      url:
        description: 'URL of the webpage to screenshot'
        required: false
        default: 'https://benjennings.design'
permissions:
  contents: write
jobs:
  capture_screenshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Puppeteer and jimp
        run: npm install puppeteer jimp
      - name: Create Screenshots Directory
        run: mkdir -p screenshots
      - name: Create screenshot script
        run: |
          cat << EOF > take_screenshot.js
          const puppeteer = require('puppeteer');
          const Jimp = require('jimp');

          async function takeScreenshot() {
            try {
              const browser = await puppeteer.launch({ args: ['--no-sandbox'] });
              const page = await browser.newPage();
              const url = process.env.INPUT_URL || 'https://benjennings.design';
              await page.goto(url, { waitUntil: 'networkidle2' });
              const pngBuffer = await page.screenshot();
              await browser.close();

              const image = await Jimp.read(pngBuffer);
              const filepath = 'screenshots/screenshot.bmp';
              await image.writeAsync(filepath);
              console.log('Screenshot saved to', filepath);
            } catch (error) {
              console.error('Error taking screenshot:', error);
              process.exit(1);
            }
          }

          takeScreenshot();
          EOF
      - name: Take Screenshot
        run: node take_screenshot.js
      - name: Commit Screenshot
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Add new screenshot [skip ci]'
          file_pattern: screenshots/*.bmp
