name: Take Webpage Screenshot
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
    inputs:
      url:
        description: 'URL of the webpage to screenshot'
        required: false
        default: 'https://benjennings.design'
permissions:
  contents: write
jobs:
  capture_screenshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Puppeteer
        run: npm install puppeteer
      - name: Create Screenshots Directory
        run: mkdir -p screenshots
      - name: Take Screenshot and Convert to BMP
        run: |
          node -e '
          const puppeteer = require("puppeteer");
          (async () => {
            try {
              const browser = await puppeteer.launch({ args: ["--no-sandbox"] });
              const page = await browser.newPage();
              await page.setViewport({
                width: 480,
                height: 800,
                deviceScaleFactor: 1,
              });
              const url = process.env.INPUT_URL || "https://benjennings.design";
              await page.goto(url, { waitUntil: "networkidle2" });
              await page.screenshot({ path: "screenshots/screenshot.png", fullPage: false });
              await browser.close();
              console.log("Screenshot saved as PNG");
            } catch (error) {
              console.error("Error taking screenshot:", error);
              process.exit(1);
            }
          })();
          '
          convert screenshots/screenshot.png -resize 480x800! screenshots/screenshot.bmp
          rm screenshots/screenshot.png
          echo "Screenshot converted to BMP (480x800)"
      - name: Commit Screenshot
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Add new screenshot [skip ci]'
          file_pattern: screenshots/*.bmp
